### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by behring5** [sheshenia/bamboobulk#4]
First of all: awesome tool. Love it.

Initially I installed it from the webstore, but it didn't work. I recognized that the content.js is doing a fetch from 
` https://ninjaone.bamboohr.com/timesheet/clock/entries` , which is blocked due to CORS policy.

After I changed the URL to the URL of my companies bamboo it worked flawlessly.

I'm not shure if its an issue due to the security settings of my companys bamboo instance, but maybe its necessary to add an option for the user to add their own bambooHR subdomain URL.

**Comment by sheshenia** [comment]
Hi @behring5 
Nice catch. Sorry for the delay in reaction. The fix is coming soon.
Another improvement I want to implement is the ability to edit the previous pending working period.
I am also looking for ways to sync with Outlook calendar.
